### ISSUE TITLE
Have some info on the page about what repliear is

### ISSUE THREAD

**Issue by grgbkr** [rocicorp/repliear#80]
Show modal on page load.

Describe what this demo is.
Link to replicache website.
Link to video showing off repliear.
Give some hints on what to try.

Have button in bottom of left nav to re-show this modal.

**Comment by phritz** [comment]
have query string that disables model if there is one so can show initial load in video

**Comment by aboodman** [comment]
# About this Demo

Repliear is a tribute to the [Linear issue tracker](https://linear.app/), built with [Replicache](https://replicache.dev), [Next.js](https://nextjs.org/), and [Supabase](https://supabase.com/).

Linear's killer feature is its performance: Every interaction throughout the UI responds instantly, with no spinners or any other indication that server communication is happening. It feels like the data is local. Additionally, the Linear UI continuously updates automatically from the server. Anytime a user changes something, all users' views update immediately to reflect the change.

In this demo we have recreated a subset of the Linear experience with Replicache, focusing on the distinctive features of Linear that are hard to build without something like Replicache.

# Key Features

## Substantial Dataset

This demo contains the entire React issue database as of mid-April 2022. It comprises about 11 thousands issues and about 50 MB of structured data.

## Instant UI Resopnsiveness

Scrolling, issue creation, issue modification, and view transition are all instant.

todo: gifs?

## Complex filters

Use the filter picker to choose one or more filters. The UI updates instantly, with zero network requests.

todo: gif

## Optimistic Updates Everywhere

There are zero spinners, and no indication that updates are optimistic at all. Even minor details like the number of active issues update optimistically.

todo: gif

## Realtime Sync Throughout

Modifying issues in the main issue or detail view, reflects automatically in other views, including kanban.

todo: gif

# Learn More

Replicache is the best way to build applications like Linear.  Learn more at replicache.dev, or come visit us in [Discord](https://discord.replicache.dev).

Check out the source for this demo at [github.com/rocicorp/repliear](https://github.com/rocicorp/repliear).
